### ISSUE TITLE
Using dataDir option results in a crash

### ISSUE THREAD

**Issue by Dhar** [andviro/grayproxy#5]
I've tried this with different directories, with and without a trailing slash, with a bound directory, and none of them work.  I always get a crash similar to:
```
2017/12/20 00:53:31 Added input 0 at udp://:12201
2017/12/20 00:53:31 Added output 0: http://graylog:12201/gelf
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5591d35edd5f]

goroutine 19 [running]:
github.com/andviro/grayproxy/vendor/github.com/nsqio/go-diskqueue.(*diskQueue).writeOne(0xc4200d6000, 0xc42010c000, 0x352, 0x600, 0x0, 0x0)
	/go/src/github.com/andviro/grayproxy/vendor/github.com/nsqio/go-diskqueue/diskqueue.go:349 +0x78f
github.com/andviro/grayproxy/vendor/github.com/nsqio/go-diskqueue.(*diskQueue).ioLoop(0xc4200d6000)
	/go/src/github.com/andviro/grayproxy/vendor/github.com/nsqio/go-diskqueue/diskqueue.go:647 +0x306
created by github.com/andviro/grayproxy/vendor/github.com/nsqio/go-diskqueue.New
	/go/src/github.com/andviro/grayproxy/vendor/github.com/nsqio/go-diskqueue/diskqueue.go:134 +0x2eb
```

What might be going on, and how do I investigate?

**Comment by andviro** [comment]
Hi there! Thanks for pointing this out. Somehow my non-vendored version of go-diskqueue happily accepted nil as a logf function. Now it's not the case. Fixed this in de721aaa1f8a8d231dad7c6a783f17c9c13ebb1b
